
// Generated by https://quicktype.io

export interface Company {

  symbol:             string;
  companyName:        string;
  marketCap:          number;
  sector:             string;
  industry:           null;
  beta:               number;
  price:              number;
  lastAnnualDividend: number;
  volume:             number;
  exchange:           string;
  exchangeShortName:  string;
  country:            string;
  isEtf:              boolean;
  isActivelyTrading:  boolean;
}

export interface ShortCompany {

  symbol:             string;
  name:               string;
  sector:             string;
  industry:           null;
  price:              number;
  exchange:           string;
  country:            string;
}
